# Array operations in Numpy

### Using np.dot() : Matrix multiply to a vector

행렬 $X(m,n)$와 벡터 $t(n)$의 곱셈은 다음 중 하나를 사용합니다.
* **numpy.dot(X,t)**  
* **X.dot(t)**

$$ 
X t = \begin{bmatrix} 
x_{11} & x_{12} & \cdots & x_{1,n} \\
x_{21} & x_{22} & \cdots & x_{2,n} \\
\vdots & \vdots & \vdots & \vdots \\
x_{m1} & x_{m2} & \cdots & x_{m,n} \\
\end{bmatrix} 
\begin{bmatrix} 
t_{1}\\
t_{2} \\
\vdots\\
t_{n}\\
\end{bmatrix}
=
\begin{bmatrix} 
h_{1}\\
h_{2} \\
\vdots\\
h_{n}\\
\end{bmatrix}
$$

In [10]:
import numpy as np
n = 10
m = 6
X = np.arange(n*m).reshape(n,m)
t = X[9,:]
print('X shape : ', X.shape, ', t shape : ',t.shape)

X shape :  (10, 6) , t shape :  (6,)


In [11]:
np.dot(X,t)

array([  865,  2899,  4933,  6967,  9001, 11035, 13069, 15103, 17137,
       19171])

In [12]:
X.dot(t)

array([  865,  2899,  4933,  6967,  9001, 11035, 13069, 15103, 17137,
       19171])

### 배열 요소간의 연산 (array element-wise operation)

벡터와 벡터의 요소들 간의 연산시는 일반적인 산술 연산자가 사용된다.
$$
\begin{bmatrix} 
t_{1}\\
t_{2}\\
\vdots\\
t_{n}\\
\end{bmatrix} +, -, *, /
\begin{bmatrix} 
y_{1}\\
y_{2}\\
\vdots\\
y_{n}\\
\end{bmatrix} = 
\begin{bmatrix} 
er_{1}\\
er_{2}\\
\vdots\\
er_{n}\\
\end{bmatrix}
$$

**주의**: 두 벡터의 모양이 같아야 합니다. 예를 들어, (3,)과 (3,1)은 다른 모양으로 간주되어, 일반 요소간 연산이 아닌 broadcasting 연산이 수행됩니다.

In [13]:
h = X.dot(t)
y = X[:,0]
print('h shape : ', h.shape, ', y shape : ',y.shape)

h shape :  (10,) , y shape :  (10,)


In [62]:
h - y # Element-wise operation h + y, h * y, h / y

array([  865,  2893,  4921,  6949,  8977, 11005, 13033, 15061, 17089,
       19117])

In [16]:
yy = X[:,0:1]
print('h shape : ', h.shape, ', yy shape : ',yy.shape)
h - yy         # Note : broadcasting operation

h shape :  (10,) , yy shape :  (10, 1)


array([[  865,  2899,  4933,  6967,  9001, 11035, 13069, 15103, 17137,
        19171],
       [  859,  2893,  4927,  6961,  8995, 11029, 13063, 15097, 17131,
        19165],
       [  853,  2887,  4921,  6955,  8989, 11023, 13057, 15091, 17125,
        19159],
       [  847,  2881,  4915,  6949,  8983, 11017, 13051, 15085, 17119,
        19153],
       [  841,  2875,  4909,  6943,  8977, 11011, 13045, 15079, 17113,
        19147],
       [  835,  2869,  4903,  6937,  8971, 11005, 13039, 15073, 17107,
        19141],
       [  829,  2863,  4897,  6931,  8965, 10999, 13033, 15067, 17101,
        19135],
       [  823,  2857,  4891,  6925,  8959, 10993, 13027, 15061, 17095,
        19129],
       [  817,  2851,  4885,  6919,  8953, 10987, 13021, 15055, 17089,
        19123],
       [  811,  2845,  4879,  6913,  8947, 10981, 13015, 15049, 17083,
        19117]])

### Using np.matmul() : Matrix multiply to a vector

ndarray 를 **numpy.matrix()**를 사용하여 행렬로 케스팅하면, 
행렬 $X(n,m)$와 벡터 $t(m)$의 곱셈은 다음 중 하나를 사용합니다.
* **numpy.matmul(X,t)**  
* **X @ t** or **X * t**

**주의** 연산속도의 효율성이 좋지 않아 실제 계산에서는 사용하지 않음, 하지만 코딩에 선형대수식을 그대로 사용이 가능한 장점이 있음.


In [1]:
print('X shape : ', X.shape, ', t shape : ',t.shape)
Xt = np.matmul(X,t) # 결과가 열벡터가 아닌 행벡터임을 주의 !!!
print(Xt)
print(Xt.shape)

NameError: name 'X' is not defined

In [35]:
Xm = np.matrix(X)
tm = np.matrix(t)
print('Xm shape : ', Xm.shape, ', tm shape : ',tm.shape, ', tm.T shape : ',tm.T.shape )
# np.matmul(Xm,tm)  <==== This cause Error.
hm = np.matmul(Xm,tm.T)
print(hm)
print(hm.shape)

Xm shape :  (10, 6) , tm shape :  (1, 6) , tm.T shape :  (6, 1)
[[  865]
 [ 2899]
 [ 4933]
 [ 6967]
 [ 9001]
 [11035]
 [13069]
 [15103]
 [17137]
 [19171]]
(10, 1)


In [58]:
Xm @ tm.T  # = Xm * tm.T 

matrix([[  865],
        [ 2899],
        [ 4933],
        [ 6967],
        [ 9001],
        [11035],
        [13069],
        [15103],
        [17137],
        [19171]])

In [68]:
hm = np.matmul(Xm,tm.T)
ym = np.matrix(X[:,0])

print('hm shape : ', hm.shape, ', ym shape : ',ym.shape, 'ym.T shape : ',ym.T.shape)
# hm - ym <=== This cause broadcasting operation
hm - ym.T
hm + ym.T
np.multiply(hm,ym.T)   # hm * ym.T 는 행렬 곱셈이 됨
hm / (ym.T + 0.0001)

hm shape :  (10, 1) , ym shape :  (1, 10) ym.T shape :  (10, 1)


matrix([[8.65000000e+06],
        [4.83158614e+02],
        [4.11079908e+02],
        [3.87053405e+02],
        [3.75040104e+02],
        [3.67832107e+02],
        [3.63026769e+02],
        [3.59594382e+02],
        [3.57020090e+02],
        [3.55017861e+02]])